#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/5032c3b5-08d7-421d-b7e1-83b1dc3175d6 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool drink1;
  bool drink2;
  bool drink3;
  bool drink4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Drink1 is READ_WRITE variable, onDrink1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onDrink1Change()  {
    if(drink1){Serial.println("1");}
  else{Serial.println("0");}
}

/*
  Since Drink2 is READ_WRITE variable, onDrink2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onDrink2Change()  {
  if(drink2){Serial.println("2");}
  else{Serial.println("0");}
}

/*
  Since Drink3 is READ_WRITE variable, onDrink3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onDrink3Change()  {
    if(drink3){Serial.println("3");}
  else{Serial.println("0");}
}

/*
  Since Drink4 is READ_WRITE variable, onDrink4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onDrink4Change()  {
    if(drink4){Serial.println("4");}
  else{Serial.println("0");}
}
