// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d0977a6a-f8ea-4cc6-a112-900607e8b30b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDrink1Change();
void onDrink2Change();
void onDrink3Change();
void onDrink4Change();

bool drink1;
bool drink2;
bool drink3;
bool drink4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(drink1, READWRITE, ON_CHANGE, onDrink1Change);
  ArduinoCloud.addProperty(drink2, READWRITE, ON_CHANGE, onDrink2Change);
  ArduinoCloud.addProperty(drink3, READWRITE, ON_CHANGE, onDrink3Change);
  ArduinoCloud.addProperty(drink4, READWRITE, ON_CHANGE, onDrink4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
